version: 2.1

jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: |
            echo "sad as hell" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: "Say hello"
          command: |
           cat ~/output.txt

workflows:
  say-hello-workflow:
    jobs:
      - print_hello
      - print_world
